<?php

namespace Elearning\CoursesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReflectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReflectionRepository extends EntityRepository
{
    public function findByStudent($studentId)
    {
        return $this->createQueryBuilder('r')
            ->where('r.student = :studentId')
            ->setParameter('studentId', $studentId)
            ->orderBy('r.studentCreatedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findByTeacher($teacherId)
    {
        return $this->createQueryBuilder('r')
            ->where('r.teacher = :teacherId')
            ->setParameter('teacherId', $teacherId)
            ->orderBy('r.studentCreatedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    // Helper to find reflections for courses where the user is a teacher, 
    // even if not explicitly assigned as the teacher in the reflection record yet (if that's how it works)
    // For now assuming the reflection record has the teacher assigned or we filter by courses the teacher teaches.
    // Based on requirements, "Teacher sees attendance statistics... and can provide..." suggests they have assigned groups/courses.

    public function findUnreadByTeacher($teacherId)
    {
        return $this->createQueryBuilder('r')
            ->where('r.teacher = :teacherId')
            ->andWhere('r.isReadByTeacher = :isRead')
            ->setParameter('teacherId', $teacherId)
            ->setParameter('isRead', false)
            ->getQuery()
            ->getResult();
    }

    public function findUnreadByStudent($studentId)
    {
        return $this->createQueryBuilder('r')
            ->where('r.student = :studentId')
            ->andWhere('r.isReadByStudent = :isRead')
            ->andWhere('r.teacherResponse IS NOT NULL')
            ->setParameter('studentId', $studentId)
            ->setParameter('isRead', false)
            ->getQuery()
            ->getResult();
    }
}
